apiVersion: apps/v1
kind: Deployment
metadata:
  name: podexec
  namespace: podexec
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: podexec
          image: ghcr.io/mchmarny/podexec:latest
